name: ci project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8 pytest-cov

    - name: linting standards
      run: flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

    - name: run tests
      run: pytest --cov=. --cov-fail-under=80 test_greeting.py

    - name: build
      run: python -m py_compile greeting.py

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}